name: Package and Publish on Release

on:
  release:
    types: [created]

jobs:
  package-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Set up Java
        uses: actions/setup-java@v1.4.4
        with:
          java-version: '17'
      - name: Build without tests
        run: mvn package -DskipTests
      - name: Build and test
        run: mvn package
      - name: Publish package
        uses: actions/upload-artifact@v3.1.2
        with:
          name: ics-${{ github.sha }}
          path: target/ics.jar
